module.exports={
    case_01:{
        input:{
            name:'arafat',
            email:'arafat@gmail.com',
            password:'1234'
        },
    },
    case_02:{
        input:{
            name:'',
            email:'arafat1194@gmail.com',
            password:'1234'
        },
    },
    case_03:{
        input:{
            name:'arafat',
            email:'arafat1194',
            password:'1234'
        },
    },
    case_04:{
        input:{
            name:'arafat',
            email:'arafat1194@gmail.com',
            password:''
        },
    },
};